### PR TITLE
Match default names KiCad generates for inner layers

### PR DESCRIPTION
**Pull request by mithro**
KiCad generates inner layer names like;
- XXX-In1_Cu.gbr
- XXX-In2_Cu.gbr

### CODE REVIEW

**Comment by CapnKernel** [comment]
Yes please!

**Comment by CapnKernel** [comment]
Yes please!

**Comment by hadleyrich** [comment]
Thanks for the pull. I will implement this with a few changes.

**Comment by mithro** [comment]
Is this deployed?

**Comment by hadleyrich** [comment]
Yes

**Pull request closed without merging**
